// <auto-generated />
using System;
using CampoVerde.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CampoVerde.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260713141314_CreateUsuarioTable")]
    partial class CreateUsuarioTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CampoVerde.Models.AlimentoBovino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadDisponible")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Categoria")
                        .HasColumnType("integer");

                    b.Property<decimal>("CostoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("NivelAlerta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Unidad")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AlimentosBovinos");
                });

            modelBuilder.Entity("CampoVerde.Models.Animal", b =>
                {
                    b.Property<int>("IdAnimal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAnimal"));

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("fechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("imagen")
                        .HasColumnType("text");

                    b.Property<string>("lote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("pesoActual")
                        .HasColumnType("double precision");

                    b.Property<string>("raza")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdAnimal");

                    b.ToTable("Animales");
                });

            modelBuilder.Entity("CampoVerde.Models.Gasto", b =>
                {
                    b.Property<int>("IdGasto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdGasto"));

                    b.Property<int>("Categoria")
                        .HasColumnType("integer");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdAnimal")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdGasto");

                    b.HasIndex("IdAnimal");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("CampoVerde.Models.Ingreso", b =>
                {
                    b.Property<int>("IdIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdIngreso"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdAnimal")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdIngreso");

                    b.HasIndex("IdAnimal");

                    b.ToTable("Ingresos");
                });

            modelBuilder.Entity("CampoVerde.Models.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("CampoVerde.Models.Parto", b =>
                {
                    b.Property<int>("IdParto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdParto"));

                    b.Property<string>("CodigoCria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstadoCria")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaParto")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdAnimal")
                        .HasColumnType("integer");

                    b.Property<string>("NombreCria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<double>("PesoCria")
                        .HasColumnType("double precision");

                    b.Property<string>("SexoCria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdParto");

                    b.HasIndex("IdAnimal");

                    b.ToTable("Partos");
                });

            modelBuilder.Entity("CampoVerde.Models.Potrero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RutasFotos")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Potreros");
                });

            modelBuilder.Entity("CampoVerde.Models.Produccion", b =>
                {
                    b.Property<int>("IdProduccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProduccion"));

                    b.Property<int>("IdAnimal")
                        .HasColumnType("integer");

                    b.Property<int>("Turno")
                        .HasColumnType("integer");

                    b.Property<double>("cantidadLeche")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("fechaProduccion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("observaciones")
                        .HasColumnType("text");

                    b.HasKey("IdProduccion");

                    b.HasIndex("IdAnimal");

                    b.ToTable("Producciones");
                });

            modelBuilder.Entity("CampoVerde.Models.Tarea", b =>
                {
                    b.Property<int>("IdTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTarea"));

                    b.Property<bool>("Completada")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Encargado")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdAnimal")
                        .HasColumnType("integer");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<int>("Prioridad")
                        .HasColumnType("integer");

                    b.Property<int>("estado")
                        .HasColumnType("integer");

                    b.HasKey("IdTarea");

                    b.HasIndex("IdAnimal");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("CampoVerde.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("estadoActivo")
                        .HasColumnType("boolean");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CampoVerde.Models.Vacuna", b =>
                {
                    b.Property<int>("IdVacuna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVacuna"));

                    b.Property<int>("IdAnimal")
                        .HasColumnType("integer");

                    b.Property<DateTime>("fechaAplicacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("fechaProximaAplicacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("frecuenciaMeses")
                        .HasColumnType("integer");

                    b.Property<string>("nombreVacuna")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("observaciones")
                        .HasColumnType("text");

                    b.HasKey("IdVacuna");

                    b.HasIndex("IdAnimal");

                    b.ToTable("Vacunas");
                });

            modelBuilder.Entity("CampoVerde.Models.Gasto", b =>
                {
                    b.HasOne("CampoVerde.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("IdAnimal");

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("CampoVerde.Models.Ingreso", b =>
                {
                    b.HasOne("CampoVerde.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("IdAnimal");

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("CampoVerde.Models.Parto", b =>
                {
                    b.HasOne("CampoVerde.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("IdAnimal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("CampoVerde.Models.Produccion", b =>
                {
                    b.HasOne("CampoVerde.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("IdAnimal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("CampoVerde.Models.Tarea", b =>
                {
                    b.HasOne("CampoVerde.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("IdAnimal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("CampoVerde.Models.Vacuna", b =>
                {
                    b.HasOne("CampoVerde.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("IdAnimal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });
#pragma warning restore 612, 618
        }
    }
}
